export const text = {
  vi: {
    appTitle: "Quản lý nhà trọ",
    home: "Trang chủ",
    rooms: "Phòng",
    payments: "Hóa đơn",
    tenants: "Khách thuê",
    settings: "Cài đặt",
    login: "Đăng nhập",
    logout: "Đăng xuất",
    refresh: "Làm mới",
    addRoom: "+ Thêm phòng",
    hi: "👋",
    appearance: "Giao diện",
    language: "Ngôn ngữ",
    light: "Sáng",
    dark: "Tối",
    emailPlaceholder: "Nhập email...",
    passwordPlaceholder: "Nhập mật khẩu...",
  },
  en: {
    appTitle: "Motel Manager",
    home: "Home",
    rooms: "Rooms",
    payments: "Payments",
    tenants: "Tenants",
    settings: "Settings",
    login: "Login",
    logout: "Logout",
    refresh: "Refresh",
    addRoom: "+ Add room",
    hi: "Hi",
    appearance: "Appearance",
    language: "Language",
    light: "Light",
    dark: "Dark",
    emailPlaceholder: "Email...",
    passwordPlaceholder: "Password...",
  },
};